all:
  hosts:
    windows:
      ansible_host: 192.168.1.203
      ansible_user: Administrator
      ansible_shell_type: powershell
      ansible_python_interpreter: C:/Users/Administrator/AppData/Local/Programs/Python/Python312/
    debian:
      ansible_host: 192.168.1.204
      vars:
        apache_pkg: apache2
        php_pkg: php
        apache_service: apache
        
    fedora:
      ansible_host: 192.168.1.205
      vars:
        apache_pkg: httpd
        php_pkg: php
        apache_service: httpd

    arch:
      ansible_host: 192.168.1.206

webservers:
  hosts:
    debian:
    fedora:

dbservers:
  hosts:
    arch:

fileservers:
  hosts:
    arch:

servers:
  children:
    webservers:
    dbservers:
    fileservers:
