glances_pkg: glances
dependencies_pkg: python-bottle
username: hunteroi-arch

apache_pkg: apache
apache_service: httpd
apache_glances_conf_path: /etc/httpd/conf/glances.conf
apache_conf_path: /etc/httpd/conf/httpd.conf
