- name: Upgrade hosts with APT
  tags: apt, debian
  when: ansible_facts['os_family'] == 'Debian'
  ansible.builtin.apt:
    upgrade: safe
    autoremove: true
    autoclean: true
    install_recommends: true
    update_cache: true
    state: latest

- name: Upgrade hosts with DNF
  tags: dnf, redhat, fedora
  when: ansible_facts['os_family'] == 'RedHat'
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: true

- name: Upgrade hosts with PACMAN
  tags: pacman, arch
  when: ansible_facts['os_family'] == 'Archlinux'
  community.general.pacman:
    upgrade: true
    update_cache: true

- name: Upgrade Windows hosts
  tags: windows
  when: ansible_facts['os_family'] == 'Windows'
  block:
    - name: Start upgrading
      ansible.windows.win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - UpdateRollups
          - Updates
        state: installed
    - name: Reboot
      ansible.windows.win_reboot:
        reboot_timeout: 3600
