- name: Upgrade hosts
  hosts: all
  tasks:
    - name: Upgrade hosts with APT
      become: true
      when: ansible_facts['os_family'] == 'Debian'
      ansible.builtin.apt:
        upgrade: safe
        autoremove: true
        autoclean: true
        install_recommends: true
        update_cache: true
        state: latest

    - name: Upgrade hosts with DNF
      become: true
      when: ansible_facts['os_family'] == 'RedHat'
      ansible.builtin.dnf:
        name: '*'
        state: latest
        update_cache: true

    - name: Upgrade hosts with PACMAN
      become: true
      when: ansible_facts['os_family'] == 'Archlinux'
      ansible.builtin.pacman:
        upgrade: true
        update_cache: true

- name: Install & Start web service & PHP
  hosts: webservers
  become: true
  tasks:
    - name: Populate ansible facts with services
      service_facts:

    - name: Open firewall ports
      firewalld:
        port: 80/tcp
        permanent: true
        immediate: true
        state: enabled
      when:
        - "'firewalld.service' in ansible_facts.services"

    - name: Install Apache & PHP
      ansible.builtin.package:
        name: '{{ apache_pkg }}, {{ php_pkg }}'
        state: present

    - name: Start Apache
      ansible.builtin.service:
        name: '{{ apache_service }}'
        enabled: true
        state: started
