- name: Upgrade hosts
  hosts: apt, dnf, pacman, windows
  become: true
  tasks:
    - name: Upgrade hosts with APT
      when: ansible_os_family == 'Debian'
      ansible.builtin.apt:
        upgrade: safe
        autoremove: true
        autoclean: true
        install_recommends: true
        update_cache: true
        state: latest

    - name: Upgrade hosts with DNF
      when: ansible_os_family == 'RedHat'
      ansible.builtin.dnf:
        name: "*"
        state: latest
        update_cache: true

    - name: Upgrade hosts with PACMAN
      when: ansible_os_family == 'Archlinux'
      ansible.builtin.pacman:
        upgrade: true
        update_cache: true

    # - name: Upgrade Windows hosts
    #   when: ansible_os_family == 'Windows'
    #   ansible.windows.win_updates:
    #     category_names:
    #       - CriticalUpdates
    #       - SecurityUpdates
    #       - UpdateRollups
    #       - Updates
    #     state: installed
