- name: Update Debian host with APT
  hosts: debian
  become: true
  tasks:
    - name: upgrade
      ansible.builtin.apt:
        upgrade: full
        update_cache: true
        autoremove: true
        autoclean: true
        install_recommends: true
